// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/[locale]/admin/modules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/modules">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/modules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/chat">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/clothing/items/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/clothing/items">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/clothing/items/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/clothing/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/clothing/orders">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/clothing/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/clothing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/clothing">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/clothing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/clothing/woocommerce-import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/clothing/woocommerce-import">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/clothing/woocommerce-import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/documents">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/employees/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/employees/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/employees/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/employees/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/employees/new">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/employees/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/employees">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/my-schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/my-schedule">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/my-schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/planning/[date]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/planning/[date]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/planning/[date]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/planning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/planning">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/planning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/qualifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/qualifications">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/qualifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/settings/audit-log/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/audit-log">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/settings/audit-log/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/settings/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/categories">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/settings/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/settings/departments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/departments">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/settings/departments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/settings/pay-grades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/pay-grades">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/settings/pay-grades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/settings/planning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/planning">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/settings/planning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/settings/qualification-types/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/qualification-types">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/settings/qualification-types/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/settings/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/roles">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/settings/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/settings/shift-swap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/shift-swap">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/settings/shift-swap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/settings/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/templates">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/settings/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/settings/work-sites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings/work-sites">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/settings/work-sites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/sign/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/sign/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/sign/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/swaps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/swaps">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/swaps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/notifications/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications/settings">> = Specific
  const handler = {} as typeof import("../../src/app/notifications/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/swaps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/swaps">> = Specific
  const handler = {} as typeof import("../../src/app/swaps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/modules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/modules">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/modules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/permissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/permissions">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/permissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/roles/permissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/roles/permissions">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/roles/permissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/roles">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/smart-replies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/smart-replies">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/smart-replies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/summarize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/summarize">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/summarize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/translate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/translate">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/translate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/audit-log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit-log">> = Specific
  const handler = {} as typeof import("../../src/app/api/audit-log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/calendar/shifts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/calendar/shifts">> = Specific
  const handler = {} as typeof import("../../src/app/api/calendar/shifts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/categories/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/categories/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/categories/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/categories">> = Specific
  const handler = {} as typeof import("../../src/app/api/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/broadcast/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/broadcast">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/broadcast/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/commands/task/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/commands/task">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/commands/task/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/mentions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/mentions">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/mentions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/messages/[id]/reactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/messages/[id]/reactions">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/messages/[id]/reactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/messages/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/messages/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/messages/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/recent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/recent">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/recent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/rooms/[id]/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/rooms/[id]/members">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/rooms/[id]/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/rooms/[id]/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/rooms/[id]/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/rooms/[id]/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/rooms/[id]/read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/rooms/[id]/read">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/rooms/[id]/read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/rooms/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/rooms/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/rooms/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/rooms/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/rooms">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/rooms/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/clothing/items/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clothing/items/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/clothing/items/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/clothing/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clothing/items">> = Specific
  const handler = {} as typeof import("../../src/app/api/clothing/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/clothing/orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clothing/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/clothing/orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/clothing/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clothing/orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/clothing/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/notifications/cleanup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/notifications/cleanup">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/notifications/cleanup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/daily-plans/[date]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/daily-plans/[date]">> = Specific
  const handler = {} as typeof import("../../src/app/api/daily-plans/[date]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/departments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/departments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/departments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/departments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/departments">> = Specific
  const handler = {} as typeof import("../../src/app/api/departments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/group-generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/group-generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/group-generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/preview">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/documents/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/documents/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employees/[id]/clothing-inventory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees/[id]/clothing-inventory">> = Specific
  const handler = {} as typeof import("../../src/app/api/employees/[id]/clothing-inventory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employees/[id]/portal-access/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees/[id]/portal-access/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/employees/[id]/portal-access/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employees/[id]/portal-access/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees/[id]/portal-access">> = Specific
  const handler = {} as typeof import("../../src/app/api/employees/[id]/portal-access/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employees/[id]/qualifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees/[id]/qualifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/employees/[id]/qualifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employees/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/employees/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employees/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees">> = Specific
  const handler = {} as typeof import("../../src/app/api/employees/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/modules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/modules">> = Specific
  const handler = {} as typeof import("../../src/app/api/modules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/mark-all-read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/mark-all-read">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/mark-all-read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/push/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/push/subscribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/push/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/unread-count/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/unread-count">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/unread-count/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pay-grades/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pay-grades/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/pay-grades/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pay-grades/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pay-grades">> = Specific
  const handler = {} as typeof import("../../src/app/api/pay-grades/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/qualification-types/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/qualification-types/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/qualification-types/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/qualification-types/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/qualification-types">> = Specific
  const handler = {} as typeof import("../../src/app/api/qualification-types/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/qualifications/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/qualifications/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/qualifications/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/qualifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/qualifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/qualifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/pdf/letterhead/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/pdf/letterhead">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/pdf/letterhead/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/planning/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/planning">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/planning/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/system/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/system">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/system/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/signatures/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signatures/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/signatures/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/signatures/[id]/sign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signatures/[id]/sign">> = Specific
  const handler = {} as typeof import("../../src/app/api/signatures/[id]/sign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/signatures/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signatures">> = Specific
  const handler = {} as typeof import("../../src/app/api/signatures/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/socket/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/socket">> = Specific
  const handler = {} as typeof import("../../src/app/api/socket/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/swaps/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/swaps/approve">> = Specific
  const handler = {} as typeof import("../../src/app/api/swaps/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/swaps/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/swaps/request">> = Specific
  const handler = {} as typeof import("../../src/app/api/swaps/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/swaps/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/swaps/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/swaps/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/templates/[id]/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/templates/[id]/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/templates/[id]/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/templates/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/templates/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/templates/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/templates">> = Specific
  const handler = {} as typeof import("../../src/app/api/templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/modules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/modules">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/modules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/permissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/permissions">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/permissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vacations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vacations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/vacations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vacations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vacations">> = Specific
  const handler = {} as typeof import("../../src/app/api/vacations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vehicles/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vehicles/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/vehicles/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vehicles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vehicles">> = Specific
  const handler = {} as typeof import("../../src/app/api/vehicles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vertretung/anfragen/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vertretung/anfragen">> = Specific
  const handler = {} as typeof import("../../src/app/api/vertretung/anfragen/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vertretung/offen/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vertretung/offen">> = Specific
  const handler = {} as typeof import("../../src/app/api/vertretung/offen/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/vertretung/suchen/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vertretung/suchen">> = Specific
  const handler = {} as typeof import("../../src/app/api/vertretung/suchen/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/woocommerce/import-orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/woocommerce/import-orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/woocommerce/import-orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/woocommerce/import-products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/woocommerce/import-products">> = Specific
  const handler = {} as typeof import("../../src/app/api/woocommerce/import-products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/work-sites/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/work-sites/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/work-sites/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/work-sites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/work-sites">> = Specific
  const handler = {} as typeof import("../../src/app/api/work-sites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
